name: discovery
description: A Travel Social App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animate_do: any
  smooth_page_indicator: ^1.0.0+2
  flutter_swiper_null_safety_flutter3: ^4.0.3
  country_picker: ^2.0.26
  image_picker: ^1.1.2
  image_picker_for_web: ^3.0.5
  pinput: ^5.0.0
  uuid: ^4.4.2
  intl: ^0.19.0
  video_player: ^2.9.1
  card_swiper: ^3.0.1
  another_transformer_page_view: ^2.0.1
  flutter_cache_manager: ^3.4.1
  cloud_firestore: ^5.2.1
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  firebase_storage: ^12.1.3
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  file: ^7.0.0
  google_sign_in: ^6.2.1

  percent_indicator: ^4.2.2
  cached_network_image: ^3.3.1
  flutter_spinkit: ^5.0.0
  fluttertoast: ^8.0.7
  animations: ^2.0.0
  image: ^4.0.16
  path_provider: ^2.0.2
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  timeago: ^3.3.0
  google_fonts: ^4.0.4
  image_cropper: ^8.0.1
  ionicons: ^0.2.1
  loading_overlay: ^0.3.0
  like_button: ^2.0.4
  flutter_chat_bubble: ^2.0.0
  permission_handler: ^10.1.0
  rounded_loading_button: ^2.1.0
  internet_connection_checker: ^1.0.0+1
  equatable: ^2.0.5
  flutter_rating_bar: ^4.0.1
  modal_progress_hud_nsn: ^0.3.0
  progress_indicator: ^0.2.2
  firebase_messaging: ^15.0.4
  flutter_local_notifications: ^17.2.2
  device_preview: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/Discovery_logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "images/Discovery_logo.png"
    background_color: "0xff205065"
    theme_color: "0xff205065"

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/splash/
    - images/categories/
    - images/recommended/
    - images/activities/

